routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route("admin.login");
});

Route::group(["prefix"=>"admin","namespace"=>"Admin","as"=>"admin."],function(){
    Route::middleware("guest:admin")->get("login","LoginCont@index")->name("login");
    Route::middleware("guest:admin")->post("login","LoginCont@doLogin")->name("login.post");

    Route::group(["middleware"=>"auth:admin"],function(){
        Route::view("dashboard","dashboard")->name("dashboard");
        Route::get("logout","LoginCont@doLogout")->name("logout");

        Route::group(["prefix"=>"product","as"=>"product.","namespace"=>"Product"],function(){
            Route::get("/","ProductCont@index")->name("index");
            Route::post("/","ProductCont@store")->name("store");
            Route::get("data","ProductCont@data")->name("data");

            Route::group(["prefix"=>"category","as"=>"category."],function(){
                Route::get("/","CategoryCont@index")->name("index");
                Route::post("/","CategoryCont@store")->name("store");
                Route::get("data","CategoryCont@data")->name("data");
                Route::get("{id}/destroy","CategoryCont@destroy")->name("destroy");
            });
        });

        Route::group(["prefix"=>"branch","as"=>"branch.","namespace"=>"Branch"],function(){
            Route::get("/","BranchCont@index")->name("index");
            Route::post("/","BranchCont@store")->name("store");
            Route::get("data","BranchCont@data")->name("data");
            Route::get("{id}/destroy","BranchCont@destroy")->name("destroy");

            Route::get("{branch_id}/product","BranchCont@product_list")->name("product_list");
            Route::get("{branch_id}/product/data","BranchCont@product_list_data")->name("product_list.data");
            Route::post("/update_product_price","BranchCont@update_product_price")->name("product_list.update_price");
        });

        Route::group(["prefix"=>"employee","as"=>"employee.","namespace"=>"Employee"],function(){
            Route::get("/","EmployeeCont@index")->name("index");
            Route::get("data","EmployeeCont@data")->name("data");
            Route::post("store","EmployeeCont@store")->name("store");
            Route::post("update","EmployeeCont@update")->name("update");
            Route::get("{id}/destroy","EmployeeCont@destroy")->name("destroy");
        });
    });
});

resources/views/partials/errors.blade.php
<script>
    @if($errors->any())
        @foreach($errors->all() as $error)
            toastr.error('{{ $error }}');
        @endforeach
    @endif
</script>

resources/views/partials/sidebar_admin.blade.php
<ul class="sidebar-menu" data-widget="tree">
    <!-- Optionally, you can add icons to the links -->
    <li class=""><a href="{{ route("admin.dashboard") }}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-archive"></i> <span>Produk</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu" style="display: none;">
            <li><a href="{{ route("admin.product.index") }}"><i class="fa fa-circle-o"></i> Daftar Produk</a></li>
            <li><a href="{{ route("admin.product.category.index") }}"><i class="fa fa-circle-o"></i> Kategori Produk</a></li>
        </ul>
    </li>

    <li class=""><a href="{{ route("admin.employee.index") }}"><i class="fa fa-user-secret"></i> <span>Pegawai</span></a></li>
    <li class=""><a href="{{ route("admin.branch.index") }}"><i class="fa fa-building-o"></i> <span>Gerai</span></a></li>
    {{--<li class=""><a href="{{ route("admin.branch.index") }}"><i class="fa fa-money"></i> <span>Keuangan</span></a></li>--}}

    {{--<li class="treeview">--}}
        {{--<a href="#">--}}
            {{--<i class="fa fa-book"></i> <span>Laporan</span>--}}
            {{--<span class="pull-right-container">--}}
              {{--<i class="fa fa-angle-left pull-right"></i>--}}
            {{--</span>--}}
        {{--</a>--}}
        {{--<ul class="treeview-menu" style="display: none;">--}}
            {{--<li><a href="#"><i class="fa fa-circle-o"></i> Berdasarkan Tanggal</a></li>--}}
            {{--<li><a href="#"><i class="fa fa-circle-o"></i> Berdasarkan Jam</a></li>--}}
            {{--<li><a href="#"><i class="fa fa-circle-o"></i> Berdasarkan Jenis Order</a></li>--}}
            {{--<li><a href="#"><i class="fa fa-circle-o"></i> Menu terlaris</a></li>--}}
        {{--</ul>--}}
    {{--</li>--}}
</ul>

resources/views/partials/success.blade.php
<script>
    @if(session()->has("success"))
    toastr.success('{{ session("success") }}');
    @endif
</script>