routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route("admin.login");
});

Route::group(["prefix"=>"admin","namespace"=>"Admin","as"=>"admin."],function(){
    Route::middleware("guest:admin")->get("login","LoginCont@index")->name("login");
    Route::middleware("guest:admin")->post("login","LoginCont@doLogin")->name("login.post");

    Route::group(["middleware"=>"auth:admin"],function(){
        Route::view("dashboard","dashboard")->name("dashboard");
        Route::get("logout","LoginCont@doLogout")->name("logout");

        Route::group(["prefix"=>"product","as"=>"product.","namespace"=>"Product"],function(){
            Route::get("/","ProductCont@index")->name("index");
            Route::post("/","ProductCont@store")->name("store");
            Route::get("data","ProductCont@data")->name("data");

            Route::group(["prefix"=>"category","as"=>"category."],function(){
                Route::get("/","CategoryCont@index")->name("index");
                Route::post("/","CategoryCont@store")->name("store");
                Route::get("data","CategoryCont@data")->name("data");
                Route::get("{id}/destroy","CategoryCont@destroy")->name("destroy");
            });
        });

        Route::group(["prefix"=>"branch","as"=>"branch.","namespace"=>"Branch"],function(){
            Route::get("/","BranchCont@index")->name("index");
            Route::post("/","BranchCont@store")->name("store");
            Route::get("data","BranchCont@data")->name("data");
            Route::get("{id}/destroy","BranchCont@destroy")->name("destroy");

            Route::get("{branch_id}/product","BranchCont@product_list")->name("product_list");
            Route::get("{branch_id}/product/data","BranchCont@product_list_data")->name("product_list.data");
            Route::post("/update_product_price","BranchCont@update_product_price")->name("product_list.update_price");
        });

        Route::group(["prefix"=>"employee","as"=>"employee.","namespace"=>"Employee"],function(){
            Route::get("/","EmployeeCont@index")->name("index");
            Route::get("data","EmployeeCont@data")->name("data");
            Route::post("store","EmployeeCont@store")->name("store");
            Route::post("update","EmployeeCont@update")->name("update");
            Route::get("{id}/destroy","EmployeeCont@destroy")->name("destroy");
        });
    });
});

app/Models/Branch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    protected $guarded = ["id"];

    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot(["bp_id","product_price","product_has_stock","stock"]);
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/Admin/Branch/BranchCont.php
<?php

namespace App\Http\Controllers\Admin\Branch;

use App\Models\Branch;
use App\Models\BranchProduct;
use App\Models\Product;
use DataTables;
use Html;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BranchCont extends Controller
{
    public function index(){
        return view("branch.index");
    }

    public function data(Branch $branch){
        return Datatables::of($branch->newQuery()->with("products"))
            ->addColumn("product_count",function($model){
                $count = $model->products->count() ?? 0;

                if($count > 0){
                    $count = Html::link(route("admin.branch.product_list",["branch_id"=>$model->id]),$count);
                }

                return $count;
            })
            ->addColumn("user_count",function($model){
                return $model->users->count() ?? 0;
            })
            ->addColumn("action",function($model){
                $has_product = $model->products->count() > 0 || $model->users->count() > 0? true:false;
                $class = !$has_product ? "btn-start":"";

                $li = "<button class='btn btn-info btn-xs $class' data-toggle='modal' data-target='#modal-branch' data-id='$model->id' data-name='$model->title' data-address='$model->address' data-phone='$model->phone'><i class='fa fa-pencil'></i></button>";
                if(!$has_product){
                    $li .= "<a class='btn btn-danger btn-xs btn-last' href='".route("admin.branch.destroy",["id"=>$model->id])."' onclick='return confirm(\"Hapus Gerai $model->title ?\")'><i class='fa fa-trash'></i></a>";
                }

                return $li;
            })
            ->rawColumns(["action","product_count"])
            ->make(true);
    }

    public function product_list($branch_id, Branch $branch){
        $branch = $branch->newQuery()->findOrFail($branch_id);
        return view("branch.product",compact("branch"));
    }

    public function product_list_data($branch_id,Request $request, Product $product){
        $q = $product->newQuery()->whereHas("branches",function($q) use ($branch_id){
            $q->where("id",$branch_id);
        })->with("category");

        return DataTables::of($q)
            ->filter(function($query) use ($request){
                // filter by branch
                if($request->has("branch_id") && $request->get("branch_id") != ""){
                    $query->whereHas("branches",function($branch) use ($request){
                        $branch->where("id",$request->get("branch_id"));
                    });
                }

                // filter by category
                if($request->has("category_id") && $request->get("category_id") != ""){
                    $query->where("category_id",$request->get("category_id"));
                }

            })
            ->addColumn("in_branch_price",function($model) use ($branch_id){
                return $this->get_branch_price($model->id,$branch_id);
            })
            ->addColumn("product_has_stock",function($model) use ($branch_id){
                return $this->get_product_has_stock($model->id,$branch_id) == 1 ? "YA":"TIDAK";
            })
            ->addColumn("stock_count",function($model) use ($branch_id){
                $stock = "-";
                if($this->get_product_has_stock($model->id,$branch_id) == 1){
                    $stock = $this->get_product_stock($model->id,$branch_id);
                }
                return $stock;
            })
            ->addColumn("action",function($model) use ($branch_id){
                $p = $this->get_branch_price($model->id,$branch_id);
                $id = $this->get_branch_price_id($model->id,$branch_id);
                $with_stock = $this->get_product_has_stock($model->id,$branch_id);
                $stock = $this->get_product_stock($model->id,$branch_id);
                $li = "<button
                                class='btn btn-info btn-xs'
                                data-toggle='modal'
                                data-target='#modal-product'
                                data-id='$id'
                                data-sellprice='$p'
                                data-withstock='$with_stock'
                                data-stock='$stock'
                                ><i class='fa fa-pencil'></i></button>";

                return $li;
            })
            ->make(true);
    }

    public function store(Request $request,Branch $branch){
        $branch->newQuery()->updateOrCreate(["id"=>$request->input("id")],$request->except("_token","id"));
        return back()->withSuccess("Gerai tersimpan.");
    }

    public function destroy($id,Branch $branch){
        $f = $branch->newQuery()->findOrFail($id);

        if($f->products->count() > 0){
            return back()->withErrors(["failed"=>"Gagal menghapus gerai, gerai memiliki produk."]);
        }

        $f->delete();
        return back()->withSuccess("Gerai berhasil dihapus.");
    }

    public function update_product_price(Request $request, BranchProduct $branchProduct){
        $branchProduct->newQuery()->where("bp_id",$request->input("id"))->first()->update(["product_price"=>$request->input("sell_price"),"product_has_stock"=>$request->input("with_stock",0),"stock"=>$request->input("stock",0)]);
        return back()->withSuccess("Data tersimpan.");
    }

    private function get_branch_price($pid,$bid){
        $b = (new BranchProduct())->newQuery()->where("product_id",$pid)->where("branch_id",$bid)->first();
        return $b->product_price;
    }

    private function get_branch_price_id($pid,$bid){
        $b = (new BranchProduct())->newQuery()->where("product_id",$pid)->where("branch_id",$bid)->first();
        return $b->bp_id;
    }

    private function get_product_has_stock($pid,$bid){
        $b = (new BranchProduct())->newQuery()->where("product_id",$pid)->where("branch_id",$bid)->first();
        return $b->product_has_stock;
    }

    private function get_product_stock($pid,$bid){
        $b = (new BranchProduct())->newQuery()->where("product_id",$pid)->where("branch_id",$bid)->first();
        return $b->stock;
    }


}

resources/views/branch/index.blade.php
@extends("master")

@section("page_header","Gerai")
@section("page_description","Daftar Gerai")
@push("contents")
    <div class="row" style="margin-bottom: 1em;">
        <div class="col-sm-12 text-right">
            <button class="btn btn-primary" data-toggle="modal" data-target="#modal-branch">Tambah Gerai</button>
        </div>
    </div>
    <div class="panel">
        <div class="panel-body">
            <div class="dataTables_wrapper form-inline dt-bootstrap">
                <table class="table table-hover dataTable" id="dtable">
                    <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Phone</th>
                        <th>Alamat</th>
                        <th>Produk</th>
                        <th>Pegawai</th>
                        <th>Created</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                </table>
            </div>

        </div>
    </div>
@endpush

@push("contents")
    <!-- Modal -->
    <div id="modal-branch" class="modal fade" role="dialog">
        <form method="post" class="modal-dialog">
            {!! csrf_field() !!}
            <input type="hidden" name="id">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Tambah/Edit Gerai</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name">Nama Gerai</label>
                        <input type="text" class="form-control" id="name" name="title" required>
                    </div>

                    <div class="form-group">
                        <label for="phone">No. Telfon</label>
                        <input type="text" class="form-control" id="phone" name="phone" required>
                    </div>

                    <div class="form-group">
                        <label for="address">Alamat</label>
                        <input type="text" class="form-control" id="address" name="address" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-default">Simpan</button>
                </div>
            </div>

        </form>
    </div>
@endpush

@push("scripts")
    <script>
        var dtable,dtableElem = $("#dtable");

        $(function(){
            dtable = dtableElem.DataTable({
                processing: true,
                serverSide: true,
                paging: false,
                searching:false,
                info:false,
                ajax: '{!! route('admin.branch.data') !!}',
                columns: [
                    { data: 'title', name: 'title' },
                    { data: 'phone', name: 'phone' },
                    { data: 'address', name: 'address' },
                    { data: 'product_count', name: 'product_count',orderable: false,searchable: false },
                    { data: 'user_count', name: 'user_count',orderable: false,searchable: false },
                    { data: 'created_at', name: 'created_at' },
                    { data: 'action', name: 'action',orderable: false,searchable: false }
                ],
                order:[
                    [5,"desc"]
                ],
                columnDefs:[
                    {className:"text-right",targets:[5]},
                    {className:"text-center",targets:[3,6,4]}
                ]
            });
        });


        $(document).on("show.bs.modal","#modal-branch",function(e){
            var trig = $(e.relatedTarget),
                name = trig.data("name") || "",
                id = trig.data("id") || "",
                address= trig.data("address") || "",
                phone = trig.data("phone") || "",
                modal = $(this);

            modal.find("input[name=title]").val(name);
            modal.find("input[name=id]").val(id);
            modal.find("input[name=address]").val(address);
            modal.find("input[name=phone]").val(phone);
        });


    </script>
@endpush

resources/views/branch/product.blade.php
@extends("master")

@section("page_header","Produk di Gerai ".$branch->title)
@section("page_description","Daftar Produk di Gerai ".$branch->title)
@push("contents")

    {{--<div class="panel">--}}
        {{--<form class="panel-body" id="f-filter">--}}
            {{--<div class="col-sm-4">--}}
                {{--{!! Form::select("branch_id",$branches,null,["class"=>"form-control","placeholder"=>"Semua Gerai","id"=>"bid"]) !!}--}}
            {{--</div>--}}

            {{--<div class="col-sm-4">--}}
                {{--{!! Form::select("category_id",$categories,null,["class"=>"form-control","placeholder"=>"Semua Kategori","id"=>"cid"]) !!}--}}
            {{--</div>--}}

            {{--<div class="col-sm-4">--}}
                {{--<button type="submit" class="btn btn-primary">Filter</button>--}}
                {{--&nbsp;--}}
                {{--<button type="button" class="btn btn-info" data-toggle="modal" data-target="#modal-product"><i class="fa fa-plus"></i> Tambah Produk</button>--}}
            {{--</div>--}}
        {{--</form>--}}
    {{--</div>--}}

    <div class="panel">
        <div class="panel-body">
            <table class="table table-hover" id="dtable">
                <thead>
                <tr>
                    <th>Nama</th>
                    <th>Harga</th>
                    <th>Harga Jual</th>
                    <th>Kategori</th>
                    <th>Dengan Stok</th>
                    <th>Jumlah Stok</th>
                    <th>Aksi</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
@endpush

@push("contents")
    <!-- Modal -->
    <div id="modal-product" class="modal fade" role="dialog">
        <form method="post" action="{{ route("admin.branch.product_list.update_price") }}" class="modal-dialog modal-sm" enctype="multipart/form-data">
            {!! csrf_field() !!}
            <input type="hidden" name="id">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Edit Produk</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="sell_price">Harga</label>
                        <input type="number" min="0" class="form-control" id="sell_price" name="sell_price" required>
                    </div>

                    <div class="form-group">
                        <label for="with-stock">Dengan Stock</label>
                        <select name="with_stock" class="form-control" required id="with-stock">
                            <option value="1">YA</option>
                            <option value="0">TIDAK</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="with-stock">Jumlah Stock</label>
                        <input type="number" class="form-control" id="stock" name="stock" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-default">Simpan</button>
                </div>
            </div>

        </form>
    </div>
@endpush

@push("scripts")
    <script>
        var dtable,dtableElem = $("#dtable");

        $(function(){
            dtable = dtableElem.DataTable({
                processing: true,
                serverSide: true,
                paging: false,
                searching:false,
                info:false,
                ajax: {
                    url: "{!! route('admin.branch.product_list.data',['branch_id'=>$branch->id]) !!}",
                },
                columns: [
                    { data: 'name', name: 'name' },
                    { data: 'base_price', name: 'base_price' },
                    { data: 'in_branch_price', name: 'in_branch_price', orderable: false,searchable: false },
                    { data: 'category.display_name', name: 'category.display_name',orderable: false,searchable: false },
                    { data: 'product_has_stock', name: 'product_has_stock',orderable: false,searchable: false },
                    { data: 'stock_count', name: 'stock_count',orderable: false,searchable: false },
                    { data: 'action', name: 'action',orderable: false,searchable: false }
                ],
                order:[
                    [0,"asc"]
                ],
                columnDefs:[
                    {className:"text-right",targets:[1,2]},
                    {className:"text-center",targets:[3,4,5,6]}
                ]
            });
        });

        $(document).on("submit","#f-filter",function(e){
            e.preventDefault();
            dtable.ajax.reload();
        });


        $(document).on("show.bs.modal","#modal-product",function(e){
            var trig = $(e.relatedTarget),
                name = trig.data("name") || "",
                id = trig.data("id") || "",
                sellPrice = trig.data("sellprice") || "",
                withStock = trig.data("withstock") || "0",
                stock = trig.data("stock") || "0",
                modal = $(this);

            modal.find("input[name=id]").val(id);
            modal.find("input[name=sell_price]").val(sellPrice);
            modal.find("select[name=with_stock]").val(withStock.toString());
            modal.find("input[name=stock]").val(stock);

        });


    </script>
@endpush