routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route("admin.login");
});

Route::group(["prefix"=>"admin","namespace"=>"Admin","as"=>"admin."],function(){
    Route::middleware("guest:admin")->get("login","LoginCont@index")->name("login");
    Route::middleware("guest:admin")->post("login","LoginCont@doLogin")->name("login.post");

    Route::group(["middleware"=>"auth:admin"],function(){
        Route::view("dashboard","dashboard")->name("dashboard");
        Route::get("logout","LoginCont@doLogout")->name("logout");

        Route::group(["prefix"=>"product","as"=>"product.","namespace"=>"Product"],function(){
            Route::get("/","ProductCont@index")->name("index");
            Route::post("/","ProductCont@store")->name("store");
            Route::get("data","ProductCont@data")->name("data");

            Route::group(["prefix"=>"category","as"=>"category."],function(){
                Route::get("/","CategoryCont@index")->name("index");
                Route::post("/","CategoryCont@store")->name("store");
                Route::get("data","CategoryCont@data")->name("data");
                Route::get("{id}/destroy","CategoryCont@destroy")->name("destroy");
            });
        });

        Route::group(["prefix"=>"branch","as"=>"branch.","namespace"=>"Branch"],function(){
            Route::get("/","BranchCont@index")->name("index");
            Route::post("/","BranchCont@store")->name("store");
            Route::get("data","BranchCont@data")->name("data");
            Route::get("{id}/destroy","BranchCont@destroy")->name("destroy");

            Route::get("{branch_id}/product","BranchCont@product_list")->name("product_list");
            Route::get("{branch_id}/product/data","BranchCont@product_list_data")->name("product_list.data");
            Route::post("/update_product_price","BranchCont@update_product_price")->name("product_list.update_price");
        });

        Route::group(["prefix"=>"employee","as"=>"employee.","namespace"=>"Employee"],function(){
            Route::get("/","EmployeeCont@index")->name("index");
            Route::get("data","EmployeeCont@data")->name("data");
            Route::post("store","EmployeeCont@store")->name("store");
            Route::post("update","EmployeeCont@update")->name("update");
            Route::get("{id}/destroy","EmployeeCont@destroy")->name("destroy");
        });
    });
});

app/Http/Controllers/Admin/Employee/EmployeeCont.php
<?php

namespace App\Http\Controllers\Admin\Employee;

use App\Http\Requests\Employee\StoreEmployeeRequest;
use App\Http\Requests\Employee\UpdateEmployeeRequest;
use App\Models\Branch;
use App\Models\User;
use DataTables;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EmployeeCont extends Controller
{
    public function index(Branch $branch){
        $branches = $branch->newQuery()->pluck("title","id");
        $roles = [
            "cashier"=>"Kasir",
            "waiters" =>"Waiters",
            "kitchen" => "Dapur"
        ];

        return view("employee.index",compact("branches","roles"));
    }

    public function data(Request $request, User $user){
        return Datatables::of($user->newQuery()->with("branch"))
            ->filter(function($query) use ($request){
                if($request->has("branch_id") && $request->get("branch_id") != ""){
                    $query->where("branch_id",$request->get("branch_id"));
                }

                if($request->has("role") && $request->get("role") != ""){
                    $query->where("role",$request->get("role"));
                }
            })
            ->addColumn("action",function($model){
                $li = "<button
                            class='btn btn-info btn-xs btn-start'
                            data-toggle='modal'
                            data-target='#modal-employee-update'
                            data-id='$model->id'
                            data-name='$model->name'
                            data-username='$model->username'
                            data-email='$model->email'
                            data-role='$model->role'
                            data-bid='$model->branch_id'
                            ><i class='fa fa-pencil'></i></button>";

                $li .= "<a class='btn btn-danger btn-xs btn-last' href='".route("admin.employee.destroy",["id"=>$model->id])."' onclick='return confirm(\"Hapus Pegawai $model->name ?\")'><i class='fa fa-trash'></i></a>";
                return $li;
            })
            ->make(true);
    }

    public function store(StoreEmployeeRequest $request,User $user){
        $request->merge(["password"=>bcrypt($request->input("password"))]);
        $user->newQuery()->create($request->except("_token"));
        return back()->withSuccess("Pegawai telah ditambahkan.");
    }

    public function update(UpdateEmployeeRequest $request,User $user){
        if($request->has("password")){
            $request->merge(["password"=>bcrypt($request->input("password"))]);
        }else{
            $request->offsetUnset("password");
        }

        $user->newQuery()->findOrFail($request->input("id"))->update($request->except("_token","id"));
        return back()->withSuccess("Data tersimpan.");
    }

    public function destroy($id,User $user){
        $x = $user->newQuery()->findOrFail($id);
        $x->delete();
        return back()->withSuccess("Pegawai telah di hapus.");
    }
}

resources/views/employee/index.blade.php
@extends("master")

@section("page_header","Pegawai")
@section("page_description","Daftar Pegawai")
@push("contents")
    <div class="panel">
        <form class="panel-body" id="f-filter">
            <div class="col-sm-4">
                {!! Form::select("branch_id",$branches,null,["class"=>"form-control","placeholder"=>"Semua Gerai","id"=>"bid-filter"]) !!}
            </div>

            <div class="col-sm-4">
                {!! Form::select("role",$roles,null,["class"=>"form-control","placeholder"=>"Semua Jabatan","id"=>"role-filter"]) !!}
            </div>

            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Filter</button>
                &nbsp;
                <button class="btn btn-info" data-toggle="modal" data-target="#modal-employee">Tambah Pegawai</button>
            </div>
        </form>
    </div>
    <div class="panel">
        <div class="panel-body">
            <div class="dataTables_wrapper form-inline dt-bootstrap">
                <table class="table table-hover dataTable" id="dtable">
                    <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Username</th>
                        <th>Jabatan</th>
                        <th>Gerai</th>
                        <th>Created</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                </table>
            </div>

        </div>
    </div>
@endpush

@push("contents")
    <!-- Modal -->
    <div id="modal-employee" class="modal fade" role="dialog">
        <form method="post" action="{{ route("admin.employee.store") }}" class="modal-dialog" id="f-employee">
            {!! csrf_field() !!}
            <input type="hidden" name="id">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Tambah Pegawai</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        {!! Form::label("name","Nama") !!}
                        {!! Form::text("name",null,["class"=>"form-control","required"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("username","Username") !!}
                        {!! Form::text("username",null,["class"=>"form-control","required"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("email","Email") !!}
                        {!! Form::email("email",null,["class"=>"form-control","required"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("password","Password") !!}
                        {!! Form::password("password",["class"=>"form-control","required"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("role","Jabatan") !!}
                        {!! Form::select("role",$roles,null,["class"=>"form-control","required"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("branch_id","Gerai") !!}
                        {!! Form::select("branch_id",$branches,null,["class"=>"form-control","required"]) !!}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-default">Simpan</button>
                </div>
            </div>

        </form>
    </div>


    <!-- Modal -->
    <div id="modal-employee-update" class="modal fade" role="dialog">
        <form method="post" action="{{ route("admin.employee.update") }}" class="modal-dialog" id="f-employee-update">
            {!! csrf_field() !!}
            <input type="hidden" name="id">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Tambah Pegawai</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        {!! Form::label("name-update","Nama") !!}
                        {!! Form::text("name",null,["class"=>"form-control","required","id"=>"name-update"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("username-update","Username") !!}
                        {!! Form::text("username",null,["class"=>"form-control","required","id"=>"username-update"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("email-update","Email") !!}
                        {!! Form::email("email",null,["class"=>"form-control","required","id"=>"email-update"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("password-update","Password") !!}
                        {!! Form::password("password",["class"=>"form-control","id"=>"password-update"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("role-update","Jabatan") !!}
                        {!! Form::select("role",$roles,null,["class"=>"form-control","required","id"=>"role-update"]) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label("branch_id-update","Gerai") !!}
                        {!! Form::select("branch_id",$branches,null,["class"=>"form-control","required","id"=>"branch_id-update"]) !!}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-default">Simpan</button>
                </div>
            </div>

        </form>
    </div>
@endpush

@push("scripts")
    <script>
        var dtable,dtableElem = $("#dtable");

        $(function(){
            dtable = dtableElem.DataTable({
                processing: true,
                serverSide: true,
                paging: false,
                searching:false,
                info:false,
                ajax: {
                    url: '{!! route('admin.employee.data') !!}',
                    data: function(d){
                        d.branch_id = $("#bid-filter").val();
                        d.role = $("#role-filter").val();
                    }
                },
                columns: [
                    { data: 'name', name: 'name' },
                    { data: 'username', name: 'username' },
                    { data: 'role', name: 'role' },
                    { data: 'branch.title', name: 'branch.title',orderable: false,searchable: false },
                    { data: 'created_at', name: 'created_at' },
                    { data: 'action', name: 'action',orderable: false,searchable: false }
                ],
                order:[
                    [0,"asc"]
                ],
                columnDefs:[
                    {className:"text-center",targets:[1,2,3,5]},
                    {className:"text-right",targets:[4]}
                ]
            });
        });


        $(document).on("show.bs.modal","#modal-employee",function(e){
            var trig = $(e.relatedTarget),
                name = trig.data("name") || "",
                id = trig.data("id") || "",
                modal = $(this);

            modal.find("input[name=display_name]").val(name);
            modal.find("input[name=id]").val(id);
        });

        $(document).on("show.bs.modal","#modal-employee-update",function(e){
            var trig = $(e.relatedTarget),
                name = trig.data("name") || "",
                id = trig.data("id") || "",
                email = trig.data("email") || "",
                role = trig.data("role") || "",
                branchId = trig.data("bid") || "",
                username = trig.data("username") || "",
                modal = $(this);

            modal.find("input[name=id]").val(id);
            modal.find("input[name=name]").val(name);
            modal.find("input[name=email]").val(email);
            modal.find("select[name=role]").val(role);
            modal.find("select[name=branch_id]").val(branchId);
            modal.find("input[name=username]").val(username);
        });

        $(document).on("submit","#f-filter",function(e){
            e.preventDefault();
            dtable.ajax.reload();
        });


    </script>
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest(\App\Http\Requests\Employee\StoreEmployeeRequest::class, '#f-employee'); !!}
    {!! JsValidator::formRequest(\App\Http\Requests\Employee\UpdateEmployeeRequest::class, '#f-employee-update'); !!}

@endpush